name: FPA
permissions:
  aws:
    iam:
    - accounts:
        ids:
        - stg-late-shift
      roles:
        predefined:
        - NRReadOnly
  azure:
    rbac:
    - subscriptions:
        all: true
        roles:
          built-in:
          - Reader
          - Billing Reader
          - Contributor
    - subscriptions:
        ids:
        - stg-my-toes
        roles:
          built-in:
          - Contributor
  cloudflare:
    role:
    - Administrator Read Only
    - Billing
  ldap:
    groups:
    - confluent_users
    - ibmcloud
team_store_id: '54332211012345'
