team_store_id: e23755f8-3b6c-4489-bc70-f55369d70991
permissions:
  ldap:
    app_users: []
    groups: []
  shell_access: false
  vault: false
  vpn: false
  aws:
    iam:
    - accounts:
        ids:
        - stg-late-shift
      roles:
        predefined:
        - NRReadOnly
